### ISSUE TITLE
instalar em ambiente linux ubuntu server 

### ISSUE THREAD

**Issue by davisvitor** [bjverde/ludsce#13]

**Comment by bjverde** [comment]
@davisvitor inicialmente não existe problema algum em usar no Linux. O Ludsce roda em ambientes em produção no Linux, basta dar as permissões corretas para as pastas

**Comment by davisvitor** [comment]
olá, obrigado por responder estou com dificuldades para Instalar o FormDin5 sobre o Adianti Template 7.5.1, creio que estou editando os arquivos errados, primeiro clono o formdin, depois edita os arquivos da pasta template?

**Comment by bjverde** [comment]
@davisvitor desculpe a demora !!  Entendi o seu problema e atualizei o tutorial de instalação e configuração do LUDSCE.

Veja se agora está claro. Se não estiver pode me chamar
https://github.com/bjverde/ludsce/blob/main/document/README_pt-BR.md

**Comment by bjverde** [comment]
@davisvitor espero que você esteja melhor !! Que bom deu certo a instalação no Ubuntu.

Vou fechar essa Issue qualquer coisa vc pode abrir outra
