### ISSUE TITLE
LUDS Sistema 

### ISSUE THREAD

**Issue by allanpordeus** [bjverde/ludsce#16]
Gostaria de adquirir o arquivo já configurado. Não consegui instalar.

**Comment by bjverde** [comment]
@allanpordeus eu já te respondi ??

**Comment by allanpordeus** [comment]
Não

Em ter, 25 de jun de 2024 21:47, Bjverde ***@***.***>
escreveu:

**Comment by bjverde** [comment]
Envia um e-mail para meu nick no gmail ! Vou te mandar o link para baixar

**Comment by allanpordeus** [comment]
Pode enviar por aqui mesmo

Em ter, 25 de jun de 2024 21:50, Bjverde ***@***.***>
escreveu:

**Comment by bjverde** [comment]
@allanpordeus link enviado !! Qualquer dúvida pode entrar em contato
